### ISSUE TITLE
Build fails on Ubuntu 14.04 with "codecvt: No such file or directory"

### ISSUE THREAD

**Issue by Kunya** [bakwc/JamSpell#23]
Hi!

Tried to install JamSpell on Ubuntu with `pip install jamspell` which ended with error

_jamspell/utils.cpp:12:23: fatal error: codecvt: No such file or directory_

Any suggestion how to overcome this thing? Did research, but found a mess with different C++ versions, standards, compilers and not sure if code update is required or some other work-around exists.

Many thanks for your advice!

**Comment by antonshilov** [comment]
Hello! I have faced the same problem on the Debian Jessi, solved it by upgrading to stretch.
Btw, it works perfectly on my Ubuntu 17.10. So the problem is clearly related to the version of gcc and stdlib.
Hope my answer can help you to solve the problem :)

**Comment by reefactor** [comment]
I had that issue. Missing codecvt probably because you have old GCC compiler.
So either you can install GCC > 5.x or use cmake options `USE_BOOST_CONVERT` (boost instead of codecvt) see https://github.com/bakwc/JamSpell/issues/12

**Comment by Kunya** [comment]
Thank you all for your help! 
Finally went with `USE_BOOST_CONVERT` option and managed to install JamSpell successfuly.

**Comment by RifatSanaullah** [comment]
how to download medical_spell model

**Comment by xihajun** [comment]
> Thank you all for your help!
> Finally went with `USE_BOOST_CONVERT` option and managed to install JamSpell successfuly.

This script worked for me
```
 cmake .. -USE_BOOST_CONVERT=ON
```
