### ISSUE TITLE
'failed building wheel' error

### ISSUE THREAD

**Issue by cl2o** [bakwc/JamSpell#65]
Hi, I've installed swig3 & can clone but not pip install jamspell — getting this error.
(jamspell) Admins-MacBook-Pro:bin me$ pip install jamspell
Collecting jamspell
  Using cached https://files.pythonhosted.org/packages/5a/16/0a808e926a835604007066085cb2183b337694a06240a99945b31fa14f27/jamspell-0.0.11.tar.gz
Building wheels for collected packages: jamspell
  Running setup.py bdist_wheel for jamspell ... error
  Complete output from command /Users/me/virtualenv/jamspell/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/vc/3v1g1x612fqbprf__p0880dr0000gp/T/pip-install-brcz77zi/jamspell/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/vc/3v1g1x612fqbprf__p0880dr0000gp/T/pip-wheel-ezr1d8z9 --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building '_jamspell' extension
  swigging jamspell.i to jamspell_wrap.cpp
  /usr/local/bin/swig -python -c++ -o jamspell_wrap.cpp jamspell.i
  creating build
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/jamspell
  creating build/temp.macosx-10.6-intel-3.6/contrib
  creating build/temp.macosx-10.6-intel-3.6/contrib/cityhash
  creating build/temp.macosx-10.6-intel-3.6/contrib/phf
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -Ijamspell -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c jamspell/lang_model.cpp -o build/temp.macosx-10.6-intel-3.6/jamspell/lang_model.o -std=c++11 -O2
  In file included from jamspell/lang_model.cpp:9:
  jamspell/lang_model.hpp:3:10: fatal error: 'unordered_map' file not found
  #include <unordered_map>
           ^~~~~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for jamspell
  Running setup.py clean for jamspell
Failed to build jamspell
Installing collected packages: jamspell
  Running setup.py install for jamspell ... error
    Complete output from command /Users/me/virtualenv/jamspell/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/vc/3v1g1x612fqbprf__p0880dr0000gp/T/pip-install-brcz77zi/jamspell/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/vc/3v1g1x612fqbprf__p0880dr0000gp/T/pip-record-x_y5l0_f/install-record.txt --single-version-externally-managed --compile --install-headers /Users/me/virtualenv/jamspell/bin/../include/site/python3.6/jamspell:
    running install
    running build_ext
    building '_jamspell' extension
    swigging jamspell.i to jamspell_wrap.cpp
    /usr/local/bin/swig -python -c++ -o jamspell_wrap.cpp jamspell.i
    creating build
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/jamspell
    creating build/temp.macosx-10.6-intel-3.6/contrib
    creating build/temp.macosx-10.6-intel-3.6/contrib/cityhash
    creating build/temp.macosx-10.6-intel-3.6/contrib/phf
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -Ijamspell -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c jamspell/lang_model.cpp -o build/temp.macosx-10.6-intel-3.6/jamspell/lang_model.o -std=c++11 -O2
    In file included from jamspell/lang_model.cpp:9:
    jamspell/lang_model.hpp:3:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/me/virtualenv/jamspell/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/vc/3v1g1x612fqbprf__p0880dr0000gp/T/pip-install-brcz77zi/jamspell/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/vc/3v1g1x612fqbprf__p0880dr0000gp/T/pip-record-x_y5l0_f/install-record.txt --single-version-externally-managed --compile --install-headers /Users/me/virtualenv/jamspell/bin/../include/site/python3.6/jamspell" failed with error code 1 in /private/var/folders/vc/3v1g1x612fqbprf__p0880dr0000gp/T/pip-install-brcz77zi/jamspell/

**Comment by themantalope** [comment]
I'm not sure where I found this, but on my mac machine, when installing with `pip` running `pip` using the `-I` and `--no-cache-dir` options seemed to do the trick. I can't say why this worked but it has. This also worked on  Ubuntu 16.04 and 18.04  for me as well. To be honest I can't recall if I had the same error you are reporting here or not. The command for some copy-pasta is:

`pip install -I --no-cache-dir jamspell`

**Comment by kothiyayogesh** [comment]
I am also facing same error on Windows 10

**Comment by bakwc** [comment]
You need some fresh cpp compiler with c++11 support.

**Comment by ljpetkovic** [comment]
> I'm not sure where I found this, but on my mac machine, when installing with `pip` running `pip` using the `-I` and `--no-cache-dir` options seemed to do the trick. I can't say why this worked but it has. This also worked on Ubuntu 16.04 and 18.04 for me as well. To be honest I can't recall if I had the same error you are reporting here or not. The command for some copy-pasta is:
> 
> `pip install -I --no-cache-dir jamspell`

It didn't work for me (macOS Big Sur 11.4):

```
Collecting jamspell
  Downloading jamspell-0.0.12.tar.gz (174 kB)
     |████████████████████████████████| 174 kB 3.0 MB/s 
Building wheels for collected packages: jamspell
  Building wheel for jamspell (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ljudmilapetkovic/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py'"'"'; __file__='"'"'/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-wheel-2u_wc_t7
       cwd: /private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_ext
  building '_jamspell' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py", line 55, in <module>
      setup(
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py", line 37, in run
      self.run_command('build_ext')
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 506, in build_extension
      sources = self.swig_sources(sources, ext)
    File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 597, in swig_sources
      swig = self.swig or self.find_swig()
    File "/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py", line 50, in find_swig
      assert subprocess.check_output([swigBinary, "-version"]).find(b'SWIG Version 3') != -1
  AssertionError
  ----------------------------------------
  ERROR: Failed building wheel for jamspell
  Running setup.py clean for jamspell
Failed to build jamspell
Installing collected packages: jamspell
    Running setup.py install for jamspell ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ljudmilapetkovic/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py'"'"'; __file__='"'"'/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-record-mnz3sc0e/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ljudmilapetkovic/opt/anaconda3/include/python3.8/jamspell
         cwd: /private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/
    Complete output (34 lines):
    running install
    running build_ext
    building '_jamspell' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py", line 55, in <module>
        setup(
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py", line 43, in run
        self.run_command('build_ext')
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 506, in build_extension
        sources = self.swig_sources(sources, ext)
      File "/Users/ljudmilapetkovic/opt/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 597, in swig_sources
        swig = self.swig or self.find_swig()
      File "/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py", line 50, in find_swig
        assert subprocess.check_output([swigBinary, "-version"]).find(b'SWIG Version 3') != -1
    AssertionError
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ljudmilapetkovic/opt/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py'"'"'; __file__='"'"'/private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-install-w6juhmz6/jamspell_a6101247fb8447f88c0b6e4fb15396ab/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/yx/k59vssnd3374p3dkld0ctjmc0000gn/T/pip-record-mnz3sc0e/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ljudmilapetkovic/opt/anaconda3/include/python3.8/jamspell Check the logs for full command output.
```

`swig` version: 4.0.2

```
SWIG Version 4.0.2

Compiled with clang++ [arm-apple-darwin20.2.0]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```

**Comment by emilysilcock** [comment]
Following the set up on their colab example seems to solve this: https://colab.research.google.com/drive/1aFk8-7nq3oAp402jjLGLpEb2Nzq210Eo#scrollTo=OK1HqdSbXpQ7

**Comment by Nbkeatley** [comment]
> Following the set up on their colab example seems to solve this: https://colab.research.google.com/drive/1aFk8-7nq3oAp402jjLGLpEb2Nzq210Eo#scrollTo=OK1HqdSbXpQ7

Their example no longer builds, unfortunately:

`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting jamspell
  Downloading jamspell-0.0.12.tar.gz (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.3/174.3 KB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: jamspell
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for jamspell (setup.py) ... error
  ERROR: Failed building wheel for jamspell
  Running setup.py clean for jamspell
Failed to build jamspell
Installing collected packages: jamspell
  error: subprocess-exited-with-error
  
  × Running setup.py install for jamspell did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for jamspell ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> jamspell

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by bakwc** [comment]
Updated example (you need to install swig3.0 and not swig), now it works.

**Comment by abhikantb** [comment]
pip install swig==3.0.6
and then pip install jamspell
it works!!!
